unstable_features = true
comment_width = 100
enum_discrim_align_threshold = 16
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
reorder_impl_items = true
struct_field_align_threshold = 16
use_field_init_shorthand = true
wrap_comments = true
